#!/usr/bin/env bash
set -euo pipefail
WORKSPACE="/home/kavia/workspace/code-generation/uttar-pradesh-tourism-infrastructure-management-system-40508-40517/infrastructure_backend"
export DEBIAN_FRONTEND=noninteractive
# helper
has() { command -v "$1" >/dev/null 2>&1; }
# Detect tools
JAVA_BIN=$(command -v java || true)
MAVEN_BIN=$(command -v mvn || true)
UNZIP_BIN=$(command -v unzip || true)
TO_INSTALL=()
if [ -z "$JAVA_BIN" ]; then TO_INSTALL+=(openjdk-17-jdk); fi
if [ -z "$MAVEN_BIN" ]; then TO_INSTALL+=(maven); fi
if [ -z "$UNZIP_BIN" ]; then TO_INSTALL+=(unzip); fi
if [ ${#TO_INSTALL[@]} -gt 0 ]; then sudo apt-get update -qq >/dev/null && sudo apt-get install -y --no-install-recommends "${TO_INSTALL[@]}" >/dev/null; fi
# Re-evaluate
JAVA_BIN=$(command -v java || true)
MAVEN_BIN=$(command -v mvn || true)
if [ -z "$JAVA_BIN" ]; then echo "ERROR: java not found; install OpenJDK 17+" >&2; exit 2; fi
if [ -z "$MAVEN_BIN" ]; then echo "ERROR: mvn not found; install maven" >&2; exit 3; fi
JAVA_BIN=$(readlink -f "$(command -v java)")
MAVEN_BIN=$(readlink -f "$(command -v mvn)")
JAVA_HOME=$(dirname "$(dirname "$JAVA_BIN")")
MAVEN_HOME=$(dirname "$(dirname "$MAVEN_BIN")")
# Extract numeric major
JAVA_VER_RAW=$(java -version 2>&1 | awk -F '"' '/version/ {print $2; exit}' || true)
if [ -z "$JAVA_VER_RAW" ]; then JAVA_VER_RAW=$(javac -version 2>&1 | awk '{print $2}' || true); fi
JAVA_MAJOR=$(printf '%s' "$JAVA_VER_RAW" | sed -E 's/^([0-9]+).*/\1/')
if ! printf '%s' "$JAVA_MAJOR" | grep -Eq '^[0-9]+$'; then echo "ERROR: unexpected java version string: $JAVA_VER_RAW" >&2; exit 4; fi
if [ "$JAVA_MAJOR" -lt 17 ]; then echo "ERROR: Java major version $JAVA_MAJOR < 17. Install OpenJDK 17+." >&2; exit 6; fi
# Prepare profile content and write atomically via sudo tee
PROFILE="/etc/profile.d/java_maven.sh"
TMP_CONTENT="# Auto-generated by setup - exports for JAVA and MAVEN\n# JAVA_HOME set to detected JDK\nexport JAVA_HOME=\"$JAVA_HOME\"\nexport MAVEN_HOME=\"$MAVEN_HOME\"\nexport PATH=\"$JAVA_HOME/bin:$MAVEN_HOME/bin:$PATH\"\nexport JAVA_TOOL_OPTIONS=\"-Xmx512m\"\nexport MAVEN_OPTS=\"-Xmx512m\"\n"
# Only replace if different
echo "$TMP_CONTENT" | sudo tee /tmp/java_maven.sh.$$ >/dev/null
if sudo [ -f "$PROFILE" ]; then
  if ! sudo cmp -s /tmp/java_maven.sh.$$ "$PROFILE"; then sudo mv /tmp/java_maven.sh.$$ "$PROFILE"; else sudo rm -f /tmp/java_maven.sh.$$; fi
else
  sudo mv /tmp/java_maven.sh.$$ "$PROFILE"
fi
sudo chmod 0644 "$PROFILE"
# Ensure workspace exists
mkdir -p "$WORKSPACE"
# Source for immediate access in this session
# shellcheck disable=SC1090
if [ -r "$PROFILE" ]; then source "$PROFILE"; fi
# Validate
java -version >/dev/null 2>&1 || { echo "ERROR: java not usable" >&2; exit 8; }
mvn -v >/dev/null 2>&1 || { echo "ERROR: mvn not usable" >&2; exit 9; }
printf 'Using JAVA_HOME=%s (version %s)\n' "$JAVA_HOME" "$JAVA_VER_RAW"
exit 0
